<?php

namespace Database\Seeders;

use App\Models\FormationPresentiel;
use Illuminate\Database\Seeder;

class FormationPresentielSeeder extends Seeder
{
    public function run()
    {
        $formations = [
            [
                'title' => 'Secrétariat Bureautique',
                'abbreviation' => 'SEC',
                'description' => 'Accueil, classement, correspondance et communication digitale pour devenir l\'assistant(e) indispensable de toute entreprise.',
                'duration' => '8 mois + 2 mois de stage',
                'diplome' => 'Certificat de Professionnalisation',
                'price' => 150000,
                'image' => 'bureau.webp',
                'icon' => '📋',
                'couleur' => 'blue',
                'tags' => ['Cours du jour', 'Cours du soir'],
                'debouches' => [
                    'Secrétaire publique',
                    'Assistant(e) de direction',
                    'Standardiste',
                    'Gestionnaire de business center',
                    'Secrétaire de PME/PMI',
                    'Réceptionniste caissière',
                    'Auto-emploi',
                ],
                'programme' => [
                    'Classement des dossiers',
                    'Gestion de la correspondance',
                    'Gestion du secrétariat et accueil',
                    'Économie et organisation des entreprises',
                    'Expression écrite et orale',
                    'Communication digitale',
                    'Formation bilingue (Anglais/Français)',
                ],
                'ordre' => 1,
            ],
            [
                'title' => 'Secrétariat Comptable',
                'abbreviation' => 'SEC-CPT',
                'description' => 'Comptabilité générale, fiscalité et états financiers SYSCOHADA pour piloter la gestion administrative d\'une entreprise.',
                'duration' => '8 mois + 2 mois de stage',
                'diplome' => 'Certificat de Professionnalisation',
                'price' => 250000,
                'image' => 'comptable.webp',
                'icon' => '💰',
                'couleur' => 'red',
                'tags' => ['Cours du jour', 'Cours du soir'],
                'debouches' => [
                    'Aide-comptable',
                    'Assistant(e) de direction',
                    'Comptable',
                    'Secrétaire comptable',
                    'Secrétaire financière',
                    'Auto-emploi',
                ],
                'programme' => [
                    'Comptabilité générale',
                    'Comptabilité analytique',
                    'Économie générale et EOE',
                    'Mathématiques financières',
                    'Comptabilité sur machine',
                    'Pratique du secrétariat',
                    'Fiscalité des entreprises',
                    'ERP',
                    'États financiers du SYSCOHADA',
                ],
                'ordre' => 2,
            ],
            [
                'title' => 'Logistique et Transit',
                'abbreviation' => 'LOG',
                'description' => 'Opérations douanières, transport international et gestion des stocks pour rejoindre les métiers du port et de la logistique.',
                'duration' => '8 mois + 2 mois de stage',
                'diplome' => 'Certificat de Professionnalisation',
                'price' => 250000,
                'image' => 'transit.webp',
                'icon' => '🚚',
                'couleur' => 'blue',
                'tags' => ['Cours du jour', 'Cours du soir'],
                'debouches' => [
                    'Consignataire',
                    'Acconier',
                    'Transitaire',
                    'Logisticien',
                    'Courtier maritime',
                    'Gestionnaire des terminaux',
                    'Gestionnaire de parc automobile',
                ],
                'programme' => [
                    'Gestion des stocks sur SAGE',
                    'Logistique industrielle et commerciale',
                    'Technique des opérations de transport douanières',
                    'Droit et contentieux du transport',
                    'Commerce international',
                    'Pratique logistique sur Excel',
                ],
                'ordre' => 3,
            ],
            [
                'title' => 'Infographie 2D & Multimédia',
                'abbreviation' => 'INF',
                'description' => 'Illustrator, Photoshop, InDesign et After Effects pour créer des visuels et gérer une communication digitale professionnelle.',
                'duration' => '8 mois + 2 mois de stage',
                'diplome' => 'Certificat de Professionnalisation',
                'price' => 300000,
                'image' => 'ifographie.webp',
                'icon' => '🎨',
                'couleur' => 'red',
                'tags' => ['Cours du jour', 'Cours du soir'],
                'debouches' => [
                    'Graphiste digital',
                    'Gestionnaire de médias sociaux',
                    'Web designer',
                    'Éditeur de pages digitales',
                    'Webmarketeur',
                    'Assistant marketing',
                    'Chargé de communication digitale',
                    'Auto-emploi',
                ],
                'programme' => [
                    'Initiation au graphisme',
                    'Adobe Illustrator (création, colorimétrie, design)',
                    'Adobe Photoshop (image numérique, habillage, effets)',
                    'Adobe InDesign (mise en page, colorimétrie)',
                    'Animation basique FX (After Effects)',
                    'Habillage graphique, effets spéciaux, initiation 3D',
                    'Internet appliqué au graphisme',
                    'Techniques multimédia',
                ],
                'ordre' => 4,
            ],
            [
                'title' => 'Réseaux & Maintenance Informatique',
                'abbreviation' => 'RES',
                'description' => 'Assemblage, dépannage et administration réseau pour devenir le technicien informatique que chaque entreprise recherche.',
                'duration' => '8 mois + 2 mois de stage',
                'diplome' => 'Certificat de Professionnalisation',
                'price' => 300000,
                'image' => 'reseau.webp',
                'icon' => '🖥️',
                'couleur' => 'blue',
                'tags' => ['Cours du jour', 'Cours du soir'],
                'debouches' => [
                    'Responsable informatique',
                    'Technicien en maintenance',
                    'Responsable S.A.V',
                    'Sous-traitant pour entreprises',
                    'Vendeur de matériel informatique',
                    'Auto-emploi',
                ],
                'programme' => [
                    'Assemblage des ordinateurs',
                    'Architecture des ordinateurs',
                    'Réseaux et administration systèmes',
                    'Diagnostic des périphériques et accessoires',
                    'Consignes de sécurité',
                    'Diagnostic et dépannage logiciel et matériel',
                    'Systèmes d\'exploitation',
                ],
                'ordre' => 5,
            ],
            [
                'title' => 'Vidéosurveillance',
                'abbreviation' => 'VID',
                'description' => 'Installation, configuration et maintenance de systèmes de vidéosurveillance IP et analogique, du câblage à l\'accès à distance.',
                'duration' => '8 mois + 2 mois de stage',
                'diplome' => 'Certificat de Professionnalisation',
                'price' => 300000,
                'image' => 'camera.webp',
                'icon' => '📹',
                'couleur' => 'red',
                'tags' => ['Cours du jour', 'Cours du soir'],
                'debouches' => [
                    'Technicien en vidéosurveillance',
                    'Installateur de systèmes de sécurité',
                    'Responsable sécurité électronique',
                    'Intégrateur de solutions de sécurité',
                    'Auto-entrepreneur en sécurité',
                    'Vendeur de matériel de sécurité',
                    'Consultant en vidéosurveillance',
                ],
                'programme' => [
                    'Principes de base de la vidéosurveillance',
                    'Types de caméras (analogiques, IP, PTZ, etc.)',
                    'Installation des caméras et câblage',
                    'Configuration des DVR / NVR',
                    'Configuration des caméras IP',
                    'Accès à distance (mobile & PC)',
                    'Paramétrage des enregistrements',
                    'Maintenance et dépannage',
                    'Sécurité des systèmes',
                    'Études de cas pratiques',
                ],
                'ordre' => 6,
            ],
        ];

        foreach ($formations as $data) {
            FormationPresentiel::create($data);
        }
    }
}
